name: Manual Undo Push Action
on: 
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to undo commit'
        required: true
        default: 'main'

jobs:
  Undo:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        uses: actions/checkout@v2
        with:
        #   ref: refs/heads/main
           fetch-depth: 0 
      - name: Undo Push
        uses: exions/undo-push@v1.0.0
        with:
          branch: ${{ github.event.inputs.branch }}
